#!/usr/bin/with-contenv sh

uid=${PUID:-1000}
gid=${PGID:-1000}
if [ $uid == 0 ]
then
    exit
fi

id cloudplow 2> /dev/null > /dev/null
cloudplow_exists=$?
if [ $cloudplow_exists != 0 ]
then
    groupadd -g $gid -r cloudplow
    useradd -u $uid -g $gid -N -r -m -s /bin/false cloudplow
    update="true"
fi

if [ $uid != $(id -u cloudplow) ] && [ $uid != 0 ]
then
    usermod -o -u $uid cloudplow
    update="true"
fi

if [ $gid != $(id -g cloudplow) ] && [ $gid != 0 ]
then
    groupmod -o -g $gid cloudplow
    update="true"
fi

if [ -n $update ]
then
    echo "GID/UID
    User uid:    $(id -u cloudplow)
    User gid:    $(id -g cloudplow)
    ------------------------------------
    "

    chown -R cloudplow:cloudplow /config
    chown -R cloudplow:cloudplow /opt/cloudplow
fi
