#!/usr/bin/with-contenv sh

if [ -n $PUID ] && [ $PUID == 0 ]
then
    exit
fi

UID=1000
if [ -n $PUID ]
then
    UID=$PUID
fi

GID=1000
if [ -n $PGID ]
then
    GID=$PGID
fi

id cloudplow 2> /dev/null > /dev/null
cloudplow_exists=$?
if [ $cloudplow_exists != 0 ]
then
    groupadd -g $GID -r cloudplow
    useradd -u $UID -g $GID -N -r -m -s /bin/false cloudplow
    update="true"
fi

if [ -n $PUID ] && [ $PUID != $(id -u cloudplow) ] && [ $PUID != 0 ]
then
    usermod -o -u "$PUID" cloudplow
    update="true"
fi

if [ -n $PGID ] && [ $PGID != $(id -g cloudplow) ] && [ $PGID != 0 ]
then
    groupmod -o -g "$PGID" cloudplow
    update="true"
fi

if [ -n $update ]
then
    echo "GID/UID
    User uid:    $(id -u cloudplow)
    User gid:    $(id -g cloudplow)
    ------------------------------------
    "

    chown -R cloudplow:cloudplow /config
    chown -R cloudplow:cloudplow /opt/cloudplow
fi
