#!/usr/bin/with-contenv sh

uid=${PUID:-1000}
user=$(getent passwd $uid | awk -F: '{print $1}')
if [ ! -f ${CLOUDPLOW_CONFIG} ]
then
    exec s6-setuidgid $user python3 /opt/cloudplow/cloudplow.py run
    echo "************************************************************************************"
    echo "INFO: Default config.json generated at ${CLOUDPLOW_CONFIG}, please configure for your environment. Exiting."
    echo "************************************************************************************"
    exit 1
fi
rclone_conf_path=$(grep -P "rclone_config_path" ${CLOUDPLOW_CONFIG} | awk -F: '{print $2}' | awk -F\" '{print $2}')
if [ ! -f ${rclone_conf_path} ]
then
    echo "************************************************************************************"
    echo "ERROR: ${CLOUDPLOW_CONFIG}:core.rclone_config_path does not point to an existing file."
    echo "************************************************************************************"
    exit 1
elif rclone --config ${rclone_conf_path} config show &> /dev/null
then
    exec s6-setuidgid $user python3 /opt/cloudplow/cloudplow.py run
    exit 0
else
    echo "************************************************************************************"
    echo "ERROR: ${CLOUDPLOW_CONFIG}:core.rclone_config_path is not a valid rclone config file."
    echo "************************************************************************************"
    exit 1
fi