name: Build 'pull_requests' Docker image from PR branch.

on:
  pull_request:
    branches:
      - develop
      - master
    paths-ignore:
      - 'README.md'
      - '.devcontainer/**'
      - '.git/**'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
           COMMIT_AUTHOR="`git log -1 --pretty=format:'%an'`"
           VCS_REF=`git rev-parse --short HEAD`
           VCS_URL=`git config --get remote.origin.url`
           docker build .
           --tag ${GITHUB_REPOSITORY}:${GITHUB_SHA}
           --build-arg $BUILD_DATE
           --build-arg $COMMIT_AUTHOR
           --build-arg $VCS_REF
           --build-arg $VCS_URL

    - name: Docker Hub Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        # Container registry password
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        # Container registry server url
        login-server: https://index.docker.io/v1/

    - name: Tag Docker image as a version of 'pull_requests' for GitHub Packages
      run: docker tag ${GITHUB_REPOSITORY}:${GITHUB_SHA} docker.pkg.github.com/${GITHUB_REPOSITORY}/pull_requests:${GITHUB_SHA}

    - name: Push Docker image to GitHub Packages
      run: docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/pull_requests:${GITHUB_SHA}