name: Delete closed PR tag from Docker Hub

on:
  pull_request:
    types: [ 'closed' ]
    branches:
      - develop
      - master
    paths-ignore:
      - 'README.md'
      - '.devcontainer/**'
      - '.git/**'
      - '.gitignore'

jobs:
  Delete_tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Extract PR number
      shell: bash
      run: env && PR=pr${GITHUB_REF#refs/pull/} && PR=${PR%/merge} && echo "##[set-output name=prnumber;]$(echo $PR)"
      id: extract_pr

    - name: Delete Docker Hub tag for closed PR
      shell: bash
      run: "curl https://hub.docker.com/v2/repositories/$GITHUB_REPOSITORY/tags/${{ steps.extract_pr.outputs.prnumber }}/ -X DELETE -H \"Authorization: JWT `curl -s -H \"Content-Type: application/json\" -X POST -d '{\"username\": \"${{ secrets.DOCKERHUB_USERNAME }}\", \"password\": \"${{ secrets.DOCKERHUB_PASSWORD }}\"}' https://hub.docker.com/v2/users/login/ | jq -r .token`\""
      id: obtain_token
