#!/usr/bin/with-contenv sh

user=cloudplow
if [ -n $PUID ] && [ $PUID == 0 ]
then
    user=root
fi
cd /opt/cloudplow
exec s6-setuidgid $user git pull
exec s6-setuidgid $user python3 -m pip install --no-cache-dir --upgrade -r requirements.txt
